from gpiozero import Button
button = Button(2)
switch = Button(19)
joystick_click = Button(21)
joystick_y = Button(20)
joystick_x = Button(16)
button.wait_for_press()
print('You pushed the button')
switch.wait_for_press()
print('You pushed the switch')
joystick_click.wait_for_press()
print('You clicked the joystick')
joystick_y.wait_for_press()
print('Joystick Y')
joystick_x.wait_for_press()
print('Joystick X')
